version: '3.8'

services:
  mongo:
    image: mongo:7.0  
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: db_chat
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"      # Porta usada pelo backend e consumer
      - "15672:15672"    # Painel web http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build: .
    container_name: fastapi-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/   # <-- adicionamos isso
    depends_on:
      - mongo
      - rabbitmq
    volumes:
      - .:/app

  consumer:
    build: .
    container_name: chat-consumer
    restart: always
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/   # <-- usa mesmo host
    depends_on:
      - rabbitmq
      - backend
    command: python -m app.rabbit.consumer  # <-- comando que fica ouvindo fila

volumes:
  mongo_data:
